# Generated by Django 3.2.16 on 2022-11-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='Введите номер телефона в формате +79001234567', max_length=12, verbose_name='Номер телефона'),
        ),
    ]
