# Generated by Django 3.2.16 on 2022-11-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Appeals',
        ),
    ]
