# Generated by Django 3.2.16 on 2022-11-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0004_alter_appeals_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeals',
            name='phone',
            field=models.BigIntegerField(help_text='Введите номер телефона в формате 89001234567', verbose_name='Номер телефона'),
        ),
    ]
