# Generated by Django 3.2.16 on 2022-11-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(help_text='Введите номер телефона в формате 89001234567', max_length=11, verbose_name='Номер телефона')),
                ('text', models.TextField(help_text='Опишите вашу проблему', verbose_name='Обращение')),
            ],
        ),
    ]
